apiVersion: v1
kind: Namespace
metadata:
  name: namespace-name
---
apiVersion: app.k8s.io/v1beta1____createApplication-apiVersion
kind: Application_________________createApplication-kind
metadata:
  name: __________________________createApplication-metadata-name
  namespace: namespace-name_______createApplication-metadata-namespace
spec:
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key:
      operator: In
      values: