apiVersion: v1______________________createChannel-namespace-resource
kind: Namespace
metadata:
  name: ____________________________createChannel-name-resource
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: ____________________________createChannel-metadata-name
  namespace: _______________________createChannel-metadata-namespace
spec:
  pathname: null
  configRef:
    name: _
  type: HelmRepo____________________createChannel-spec-type
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: null
  namespace: namespace-name