sudo: required
language: node_js

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}

matrix:
  include:
    - os: linux
      env: OSARCH=rhel7 TARGET=${TARGET_IP}
      dist: trusty
    - os: linux-ppc64le
      env: OSARCH=linux-ppc64le
      dist: trusty
    - os: linux
      env: OSARCH=linux-amd64
      dist: trusty

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

cache:
  apt: true
  directories:
    - "$TRAVIS_CACHE_DIR"

before_cache:
  - sudo rm -rf $TRAVIS_CACHE_DIR/selenium-standalone

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker
  - xvfb

before_install:
  - make init
  - source travis-env.sh

install:
  - make install

before_script:
  - make image
  - chmod +x copyright-check.sh

script:
  - make copyright-check
# - make test
# - make cicd-log-test
# - export PREV_COVERAGE_REPORT=$(curl -L -H 'Authorization:token ${GITHUB_TOKEN}' https://raw.github.ibm.com/IBMPrivateCloud/mcm-application-ui/gh-pages/coverage/coverage-summary.json)
# - node travis-scripts/enforce-coverage.js

after_success:
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push || echo "pushing to scratch"
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..." 
            echo ${DOCKER_INTEGRATION_REGISTRY}
            make docker:login DOCKER_REGISTRY=${DOCKER_INTEGRATION_REGISTRY}
            make docker:manifest-tool DOCKER_REGISTRY=${DOCKER_INTEGRATION_REGISTRY}
            make docker:multi-arch DOCKER_REGISTRY=${DOCKER_INTEGRATION_REGISTRY}
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi

after_failure:
  - |
      if [ -d "test-output" ]; then
        echo "Some jobs failed"
      fi
#        sudo apt-get install -y expect
#        mkdir selenium-test && mkdir selenium-test/$TRAVIS_JOB_NUMBER && cp -R test-output/e2e selenium-test/$TRAVIS_JOB_NUMBER
#        expect upload-selenium.sh
#        echo Selenium test failed! Result available at http://9.42.81.137:81/$TRAVIS_JOB_NUMBER/e2e/
#      fi

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local-dir: test-output
#   github-url: github.ibm.com
#   on:
#     branch: master
#

notifications:
  slack: ibm-cloudplatform:L8wJzwiKzLuYBmdQIEF1QQDt
